### ISSUE TITLE
Disable auto re-subscribe when socket is reconnected

### ISSUE THREAD

**Issue by ikhsanbdy** [goriunov/ClusterWS-Client-JS#51]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggetion
- [ ] Other

Hi, is there a way to disable auto re-subscribe when socket is reconnected ?

**Comment by goriunov** [comment]
Unfortunately at this moment not. Will add it to the version 4.0.0.

**Comment by ikhsanbdy** [comment]
Ok thanks @goriunov
