### ISSUE TITLE
Add remote start

### ISSUE THREAD

**Issue by ramjak** [goriunov/ClusterWS-Client-JS#53]
### Submitting
- [ ] Bug
- [ ] Question
- [x] Suggetion
- [ ] Other

### Details
ClusterJS v3.1.1
Linux Ubuntu 18.04

Add remote start to trigger the creation of Socket instead of connecting immediately after ClusterWS instance created. It would help rxjs to attach connect listener before the Socket connected.

AFAIK if the rxjs pipeline is too complex it will take more time before the Socket connected.

**Comment by goriunov** [comment]
Yes i thought about that, i think i wanted to add `connect ` method which would trigger actual connection to the socket. And also add `autoConnect` param for people who does not want to trigger method manually (this should call connect after everything has been set up).
